# Generated by Django 4.1.3 on 2022-11-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='ratings',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
