# Generated by Django 4.1.3 on 2022-11-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='site',
            field=models.URLField(null=True),
        ),
    ]
