# Generated by Django 4.1.3 on 2022-12-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaktus_media_parser',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
